### ISSUE TITLE
Sora editor crashes

### ISSUE THREAD

**Issue by finley9103** [TS-Code-Editor/Android-Code-Editor#13]
**Describe the bug**

I am using a old android device but sora editor crashes.
I don't have Contributor contact but only had PHANTOMLOCAL telegram.He said he can fix but he refused then.
This issue is already reported but developers ignored it

 
![IMG_20230807_203734](https://github.com/TS-Code-Editor/Android-Code-Editor/assets/141655794/a5f91874-a97e-4ef1-b5ac-ede84939c2bc)
![IMG_20230807_203718](https://github.com/TS-Code-Editor/Android-Code-Editor/assets/141655794/0f7ab5c7-74c3-466b-8c12-ee21a0f53c86)
![IMG_20230807_203622](https://github.com/TS-Code-Editor/Android-Code-Editor/assets/141655794/0b98e0cc-82de-4aaa-8b53-55cd2736e6f7)

**Comment by DevKumar00001** [comment]
Sorry for the misbehavior of PHANTOMLOCAL but I have not forgotten this issue but I can't currently fix it.
It was easy to contact main developer like me and CyberGlitch01 if you have joined discord server.
Contact me at telegram if you don't use discord -  @DevKumar001119381293

**Comment by DevKumar00001** [comment]
@PHANTOMLOCAL is executed because misleading someone.
