### ISSUE TITLE
nonfree components added with latest release

### ISSUE THREAD

**Issue by IzzySoft** [TS-Code-Editor/Android-Code-Editor#22]
Looks like with the latest release, your app is no longer fully foss:

```
Offending libs:
---------------
* Google Ads (/com/google/ads): Ads,NonFreeComp
* Google Mobile Services (/com/google/android/gms): NonFreeComp
* Firebase (/com/google/firebase): NonFreeNet,NonFreeComp
* Firebase Analytics (/com/google/firebase/analytics): NonFreeComp,Tracking
* Firebase Installations (/com/google/firebase/installations): NonFreeNet

5 offenders.
```

Was that intentionally? Could you please remove Firebase Analytics and Google Ads again (as they are not privacy friendly, to put it mildly, apart from being proprietary)? I'll have to flag [your app in my repo](https://apt.izzysoft.de/packages/android.code.editor/) now with all the 3 anti-features and have to consider removing it as it's no longer libre (5 offenders is just crossing the red line).

If you need some analytics, please take a look at [acceptable analytics](https://gitlab.com/-/snippets/1896503#acceptable-analytics) in my F-Droid snippet for alternatives. There are FOSS ways to do that.

Thanks for considering!

**Comment by DevVigilante** [comment]
> Looks like with the latest release, your app is no longer fully foss:
> 
> ```
> Offending libs:
> ---------------
> * Google Ads (/com/google/ads): Ads,NonFreeComp
> * Google Mobile Services (/com/google/android/gms): NonFreeComp
> * Firebase (/com/google/firebase): NonFreeNet,NonFreeComp
> * Firebase Analytics (/com/google/firebase/analytics): NonFreeComp,Tracking
> * Firebase Installations (/com/google/firebase/installations): NonFreeNet
> 
> 5 offenders.
> ```
> 
> Was that intentionally? Could you please remove Firebase Analytics and Google Ads again (as they are not privacy friendly, to put it mildly, apart from being proprietary)? I'll have to flag [your app in my repo](https://apt.izzysoft.de/packages/android.code.editor/) now with all the 3 anti-features and have to consider removing it as it's no longer libre (5 offenders is just crossing the red line).
> 
> If you need some analytics, please take a look at [acceptable analytics](https://gitlab.com/-/snippets/1896503#acceptable-analytics) in my F-Droid snippet for alternatives. There are FOSS ways to do that.
> 
> Thanks for considering!

Why I am receiving this issue does I logged in on any website that relates to you?

**Comment by IzzySoft** [comment]
You receive this issue because it's for your app? So whoever uses your app is affected? Does that not count? I don't understand your question. Your Readme states:

> The Android code editor is an open-source project

and I pointed out that's no longer fully true, as the app now contains proprietary components – which track who uses the app, so this is also a privacy concern. Does that not matter to you?

**Comment by DevVigilante** [comment]
> You receive this issue because it's for your app? So whoever uses your app is affected? Does that not count? I don't understand your question. Your Readme states:
> 
> > The Android code editor is an open-source project
> 
> and I pointed out that's no longer fully true, as the app now contains proprietary components – which track who uses the app, so this is also a privacy concern. Does that not matter to you?

See the privacy policy update at the last release there is a note and when you use app first time it says you to accept or not if you don't accept you will not able to use app.

**Comment by IzzySoft** [comment]
So TL;DR you will not address this issue (not even e.g. with a libre build flavor)?

**Comment by DevVigilante** [comment]
I don't know what you want, why and what is solution

**Comment by DevKumar00001** [comment]
I don't know what you want, why and what is solution

**Comment by IzzySoft** [comment]
Above mentioned libraries are proprietary. Further, they report to Google without the user's voluntary consent – and what's more, not even you can control what data they really send (as they are closed source). From past experience, you cannot trust what their documentation says on this. Which makes it a big issue for those concerned about their privacy.

A possible solution I've also pointed out above already: there are [FOSS alternatives for analytics](https://gitlab.com/-/snippets/1896503#acceptable-analytics) to replace Firebase Analytics, if you really need such. There's probably no easy alternative for Google Ads (which are a privacy nightmare per-se), which is why I mentioned [build flavors](https://developer.android.com/build/build-variants). You could e.g. provide a FOSS APK that way coming without the offending libs for those concerned, while still shipping the current setup e.g. via Google Play for those who don't mind.

So what I (and other privacy-aware folks) would want is an app that comes without the above mentioned "offenders". Removing Firebase Analytics and Google Ads will probably take care for the other 3 which most likely were just dragged in as dependencies.

Is there any chance for that?

**Comment by DevVigilante** [comment]
No bro thanks for the information but firebase is the best option and I am not using Google ads I planned for this release but suddenly I did got late approval.

**Comment by IzzySoft** [comment]
OK, thanks – then at least we know where we stand. Wish you the best for your project, but I'll remove the app then from my repo as with 4 anti-feature warnings it would confuse those using it, who expect libre and privacy-focused software in it.
