### ISSUE TITLE
Does not request storage permission in Android 13

### ISSUE THREAD

**Issue by Yeasir0032** [TS-Code-Editor/Android-Code-Editor#3]
**Description**
It saying to give permission of storage but it does not show anything in the permission page.
**Expected behavior**
It should request the permission or redirects into permission page

**Smartphone**
 - Device: Samsung F13
 - OS: Android 13

**Comment by TechnicalStudioDeveloper** [comment]
Try mannually give storage permission.I will fix it for android 13

**Comment by TechnicalStudioDeveloper** [comment]
Can I have your telegram contact @Yeasir0032 ?

**Comment by Yeasir0032** [comment]
![Screenshot_20230706_140339_Permission controller](https://github.com/TS-Code-Editor/Android-Code-Editor/assets/124646897/0c0adbe8-4f3b-406e-9900-f36132f9411f)

**Comment by Yeasir0032** [comment]
> Can I have your telegram contact @Yeasir0032 ?

@yeasir0032

**Comment by Yeasir0032** [comment]
> Try mannually give storage permission.I will fix it for android 13

It does not work like that also 
you can see the photo

**Comment by TechnicalStudioDeveloper** [comment]
Fixed in https://github.com/TS-Code-Editor/Android-Code-Editor/commit/630b0d3ca8adf723137123b1984e74271523a1ca
